### ISSUE TITLE
Style bugs: Toast Notification is missing Layer properties

### ISSUE THREAD

**Issue by havesomeleeway** [IBM/design-system-website#137]
## Detailed description

> Is this issue related to a specific component?

Working through the website to implement some component mock-ups locally. Realised that there is a slight inconsistency between the style information of [Toast Notification](http://carbondesignsystem.com/components/notification/style) vs [Modal](http://carbondesignsystem.com/components/modal/style)

> What did you expect to happen? What happened instead? What would you like to see changed?

While both components have a z-depth, the `Layer` related properties for the modal is indicated as follows:

Pop-out | 24 | 0 12px 24px 0 rgba(0,0,0,0.10);
-- | -- | --

However, the `Layer` related properties is missing for the Toast Notification.
____

The CSS Inspector tool indicates that the `box-shadow` properties for Toast Notifications is `0px 3px 3px 0 rgba(0, 0, 0, 0.1)`

![bx--toast-notification](https://user-images.githubusercontent.com/25948209/35130088-09d51102-fcfa-11e7-8acf-3d06f5d7f760.png)

This particular setting is also absent in the list of [Layer](http://carbondesignsystem.com/style/layer/overview) properties. 

![layer--settings](https://user-images.githubusercontent.com/25948209/35130108-1f12f62e-fcfa-11e7-9a2d-99266de4ba1c.png)

**Comment by marijohannessen** [comment]
@aagonzales Is toast notifications supposed to have a layer or just a normal box-shadow? It currently has the standard of `0px 3px 3px 0 rgba(0, 0, 0, 0.1)`, which is not a layer box-shadow - and I'm pretty sure that's intentional but I might be wrong.
