### ISSUE TITLE
Add "who can use Carbon" to FAQ section

### ISSUE THREAD

**Issue by aagonzales** [IBM/design-system-website#293]
We've been getting a lot of questions asking if certain teams both in IBM and outsides can use Carbon. Need to clarify that its an open source project, need to clarify relationship with IBM Cloud and growing scope of Carbon.

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-website-gatsby #33](https://github.com/carbon-design-system/carbon-website-gatsby/issues/33) via [**ZenHub**](https://www.zenhub.com/)
