### ISSUE TITLE
Search results: Links to Add-on section are broken in few places

### ISSUE THREAD

**Issue by willowbrae** [IBM/design-system-website#303]
When you use internal search with "**add-on**" keyword there are 3 results, two of them are broken links. Similar situation with **addon*

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-website-gatsby #34](https://github.com/carbon-design-system/carbon-website-gatsby/issues/34) via [**ZenHub**](https://www.zenhub.com/)
