### ISSUE TITLE
iframe bugs on data vis pages

### ISSUE THREAD

**Issue by aagonzales** [IBM/design-system-website#319]
The `code-types` & `results-button-list` (HTML, CSS, Bable, Results) is misaligned and hanging below the edge of the `embed-nav group` area.

In Data Visualization pages:
![image](https://user-images.githubusercontent.com/11670886/43605712-dfe88956-965e-11e8-89db-83804c685b53.png)

**Comment by alisonjoseph** [comment]
Looks like codepen changed something on their end, looking in to updating our codepen embed theme.

**Comment by alisonjoseph** [comment]
fixed on codepen.
