### ISSUE TITLE
swatch label error

### ISSUE THREAD

**Issue by dayzed007** [IBM/design-system-website#324]
http://www.carbondesignsystem.com/style/color/swatches

hover-row
rgba(#5596e6, 0.1) <- misrepresented

rgba(85,155,235,0.1) would be proper, or just drop the RGBA

**Comment by shinytoyrobots** [comment]
Issue moved to [carbon-design-system/carbon-website-gatsby #35](https://github.com/carbon-design-system/carbon-website-gatsby/issues/35) via [**ZenHub**](https://www.zenhub.com/)
