### ISSUE TITLE
themes.carbondesignsystem.com source code

### ISSUE THREAD

**Issue by chasestarr** [IBM/design-system-website#344]
is themes.carbondesignsystem.com open source? i did a bit of searching but couldn't find it. anyone mind pointing in the right direction?

**Comment by tw15egan** [comment]
Sure is! You can take a look at it here: https://github.com/carbon-design-system/carbon-sandbox

https://github.com/carbon-design-system/carbon-sandbox

**Comment by chasestarr** [comment]
Thanks a lot!
